from app.schemas.review import (
    IssueCategory,
    ReviewIssue,
    ReviewResponse,
    ReviewSummary,
    Severity,
    FindingStatus,
)

from app.services.github_comment_service import (
    format_review_comment,
)


def test_format_review_comment_with_findings():
    review = ReviewResponse(
        review_id="review-123",
        summary=ReviewSummary(
            critical=0,
            high=1,
            medium=1,
            low=0,
        ),
        issues=[
            ReviewIssue(
                category=IssueCategory.SECURITY,
                severity=Severity.HIGH,
                file="auth.py",
                line_start=12,
                line_end=12,
                title="Hardcoded password detected",
                description=(
                    "A password is hardcoded "
                    "in the source code."
                ),
                suggestion=(
                    "Move the credential to "
                    "an environment variable."
                ),
                confidence=0.95,
                source="bandit",
                rule_id="B105",
                pr_status=FindingStatus.INTRODUCED,
            ),
            ReviewIssue(
                category=IssueCategory.CODE_QUALITY,
                severity=Severity.MEDIUM,
                file="utils.py",
                line_start=20,
                line_end=25,
                title="Large function",
                description=(
                    "This function is longer "
                    "than recommended."
                ),
                suggestion=(
                    "Split the function into "
                    "smaller functions."
                ),
                confidence=0.8,
                source="ast",
                rule_id="large-function",
                pr_status=FindingStatus.PRE_EXISTING,
            ),
        ],
    )

    result = format_review_comment(review)

    assert "## 🤖 AI Code Review" in result
    assert "0 critical, 1 high, 1 medium, 0 low" in result
    assert "Hardcoded password detected" in result
    assert "`auth.py:12`" in result
    assert "`SECURITY`" in result
    assert "`HIGH`" in result
    assert "`INTRODUCED`" in result
    assert "`utils.py:20-25`" in result
    assert "Generated by AI Code Reviewer" in result


def test_format_review_comment_with_no_findings():
    review = ReviewResponse(
        review_id="review-456",
        summary=ReviewSummary(
            critical=0,
            high=0,
            medium=0,
            low=0,
        ),
        issues=[],
    )

    result = format_review_comment(review)

    assert "## 🤖 AI Code Review" in result
    assert "0 critical, 0 high, 0 medium, 0 low" in result
    assert "✅ No issues were detected." in result
    assert "Generated by AI Code Reviewer" in result