from app.schemas.review import ReviewResponse


def format_review_comment(
    review: ReviewResponse,
) -> str:
    lines = [
        "## 🤖 AI Code Review",
        "",
        (
            f"**Summary:** "
            f"{review.summary.critical} critical, "
            f"{review.summary.high} high, "
            f"{review.summary.medium} medium, "
            f"{review.summary.low} low"
        ),
        "",
    ]

    if not review.issues:
        lines.extend(
            [
                "✅ No issues were detected.",
                "",
                "---",
                "*Generated by AI Code Reviewer*",
            ]
        )

        return "\n".join(lines)

    lines.append("### Findings")

    for index, issue in enumerate(
        review.issues,
        start=1,
    ):
        location = ""

        if issue.file:
            location = issue.file

            if issue.line_start is not None:
                location += f":{issue.line_start}"

                if (
                    issue.line_end is not None
                    and issue.line_end != issue.line_start
                ):
                    location += f"-{issue.line_end}"

        lines.extend(
            [
                "",
                f"#### {index}. {issue.title}",
                "",
                (
                    f"**Severity:** `{issue.severity.value}`  \n"
                    f"**Category:** `{issue.category.value}`"
                ),
            ]
        )

        if location:
            lines.append(
                f"**Location:** `{location}`"
            )

        if issue.pr_status:
            lines.append(
                f"**PR Status:** `{issue.pr_status.value}`"
            )

        lines.extend(
            [
                "",
                issue.description,
                "",
                f"**Suggestion:** {issue.suggestion}",
            ]
        )

    lines.extend(
        [
            "",
            "---",
            "*Generated by AI Code Reviewer*",
        ]
    )

    return "\n".join(lines)